name: Vagrant Provision

on:
  push:
    branches:
      - main

jobs:
  vagrant-up:
    runs-on: ubuntu-latest  # Use an Ubuntu-based runner for faster execution

    steps:
      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up

      - name: ssh into box after boot
        run: vagrant ssh -c "echo 'Hello from Vagrant'"

      - name: Tear down Vagrant
        run: vagrant destroy -f
